language: rust
matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly
    include:
        - os: osx
          rust: stable

        - rust: stable
          env: FEATURES=""
        - rust: beta
          env: FEATURES=""
        - rust: nightly
          env: FEATURES=""

        - rust: stable
          env: FEATURES="--features hyper-011"
        - rust: beta
          env: FEATURES="--features hyper-011"
        - rust: nightly
          env: FEATURES="--features hyper-011"

        # minimum version
        - rust: 1.26.0
          script: cargo build

sudo: false
dist: trusty

script:
  - cargo build $FEATURES
  - cargo test -v $FEATURES
