[package]
name = "reqwest"
version = "0.0.0"
description = "higher level HTTP client library"
repository = "https://github.com/seanmonstar/reqwest"
documentation = "https://docs.rs/reqwest"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
hyper = { version = "0.9" }#, default-features = false }
log = "0.3"

[dev-dependencies]
env_logger = "0.3"
